# Site settings
title: Yassine Maaroufi - JS & Python Developer
email: yassinemaaroufi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web development portfolio | Yassine Maaroufi
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yassinemaaroufi.github.io" # the base hostname & protocol for your site
twitter_username: yassinemaaroufi
github_username:  yassinemaaroufi

# Build settings
markdown: kramdown
